### ISSUE TITLE
Spring security 디펜던시가 없어서 에러

### ISSUE THREAD

**Issue by gukin-han** [NaKaLiGoBa/Instagram#11]
#9 여기에 spring security 디펜던시가 추가가 안되어있네요!

**Comment by acisliver** [comment]
확인했습니다! 수정하겠습니다!

**Comment by acisliver** [comment]
cc313c313a136da5259d488b949ea94eb8d70de9 이 커밋을 삭제하지 않고 올렸더라구요.
c082c032483fbdfb8af15aa6e22f25b3e2a7b902 으로 해결했습니다!

**Comment by acisliver** [comment]
Close
